### ISSUE TITLE
Build/customize initial project curation page with options to create, update

### ISSUE THREAD

**Issue by broadwell** [CobwebOrg/cobweb#2]

**Comment by andrewbenedictwallace** [comment]
@broadwell I'm not sure I understand what you mean by "project curation" – is this just duplicating the project create / update issues above it?

**Comment by broadwell** [comment]
@andrewbenedictwallace Yeah I guess it's kind of redundant. My idea (based on the workflow diagram, more or less) was that the curation page might contain the project creation form and the interface features for the edit/delete options as well, so this ticket might similarly kind of encapsulate the others. Perhaps seeing the wireframes will help us think this through.

**Comment by andrewbenedictwallace** [comment]
👍
